### ISSUE TITLE
请教,kotlin语法问题

### ISSUE THREAD

**Issue by yizeliang** [2dxgujun/span#1]
初次看到,真的是被惊艳到了,原来kotlin还可以这样写,十分佩服,所以尝试去看 了下源码,对下面这块代码看的不是特别明白,我也是kotlin初学者,想了很久没有明白,所以来这里请教下您

```kotlin

fun span(init: Span.() -> Unit): Span = Span().apply {
  setGlobalStyles()
  init()
  build()
}

```
主要是`init: Span.() -> Unit` 这块代码看不懂,我仿照写了写,会报错,但是又不知道为什么您的代码没有问题,所以想您给点提示,非常感谢

**Comment by 2dxgujun** [comment]
你好，可以尝试分解开来看，首先`Span.() -> Unit`是参数`init`的类型，`() -> Unit`是[function type](https://kotlinlang.org/docs/reference/lambdas.html#higher-order-functions)，`Span.() -> Unit`表示这是一个[extension function](https://kotlinlang.org/docs/reference/extensions.html#extension-functions)，合在一起就表示这个`init`参数，是一个`Span`类的扩展函数类型，效果就是能访问这个类里面的public方法，用lambda的写法，就写成下面这样了

```kotlin
span {
    text = "Hi"
}
```

**Comment by yizeliang** [comment]
佩服,感谢指点,懂了,3Q
